#define NUM_LEDS_PER_STRIP 300
#define NUM_STRIPS 2
#define NUM_LEDS (NUM_LEDS_PER_STRIP * NUM_STRIPS)

#define BRIGHTNESS_MAX 155

#define LED_START_PIN 19
#define ENCODER_PIN_A 8
#define ENCODER_PIN_B 9
#define BUTTON_PIN 7
#define BUTTON_DELAY 5
